
# TODO     FIND A WAY TO JUST STORE THE TEXT FILE FOR YOUR QUOTES, THEN READ THOSE FILES, GET A PEXELS VIDEO QUERY FROM THEM,
# TODO     AND YOUTUBE VIDEO TAGS FOR THEM, AND SUMMARY FOR DESCRIPTION MIGHT REQUIRE A LLM
