quotes = [
    "Stars are like the memories of the universe, each one a glimpse into its past.",
    "The mind is a canvas, and thoughts are the brushstrokes that paint our reality.",
    "In the symphony of life, each experience plays a note that resonates through eternity.",
    "Time is a river, and we are the stones that shape its flow.",
    "The dance of chaos and order births the cosmos.",
    "A smile is the gravitational pull of happiness on the fabric of existence.",
    "Echoes remind us that even sound leaves a piece of itself behind.",
    "To dream is to navigate the corridors of possibility.",
    "Knowledge is the currency of civilizations, and curiosity its mint.",
    "In the garden of existence, we are both the flowers and the gardeners.",
    "Like books, our lives are written one chapter at a time, with unwritten pages awaiting our pen.",
    "Solitude is the forge where individuality is tempered.",
    "The moon is Earth's silent confidant, witnessing all of our history with patient grace.",
    "Laughter is the language that transcends the barriers of words.",
    "A puzzle is a reminder that completeness is found in the sum of its unique parts.",
    "The universe whispers its secrets in the silence between heartbeats.",
    "A tree's roots are its memoirs, holding tales of forgotten seasons.",
    "Forgiveness is the bridge between regret and renewal.",
    "Mirrors reflect more than appearances; they mirror the stories within.",
    "In the realm of thoughts, wanderers are often richer than kings.",
    "Mistakes are the sketches that precede the masterpiece of understanding.",
    "A candle's purpose is not diminished by lighting another candle.",
    "Fear is the shadow cast by the light of potential.",
    "The mind is both the architect and the architecture of belief.",
    "Rainbows remind us that beauty arises from the marriage of sun and rain.",
    "Whispers of the wind are the voices of forgotten ancestors.",
    "The heart is a map, each beat marking a new direction in the journey of emotion.",
    "Eyes are the translators of light into the poetry of vision.",
    "Through the window of dreams, we glimpse alternate realities woven by desire.",
    "Grief is the tribute we pay to love's eternal presence.",
    "The horizon is a promise, forever urging us to chase the uncharted.",
    "In the orchestra of existence, silence holds as much music as sound.",
    "Like stars, friendships are born from the interplay of distance and connection.",
    "The echo of a smile can travel farther than the smile itself.",
    "A single snowflake is a reminder that delicate beauty can transform the world.",
    "Words are vessels, carrying the cargo of our thoughts across the ocean of understanding.",
    "The pen is a bridge, allowing ideas to cross from mind to parchment.",
    "Tears cleanse the soul, like rain washing away the dust of sorrow.",
    "A moment of hesitation can be the chrysalis from which bravery emerges.",
    "The universe converses with us in the languages of coincidence and serendipity.",
    "A mirror reflects not only the exterior but the interior gaze as well.",
    "A question is a key that opens doors to uncharted chambers of knowledge.",
    "Vulnerability is the birthplace of genuine connections.",
    "The mosaic of life is built from the fragments of our experiences.",
    "In the tapestry of time, we are both weavers and threads.",
    "A labyrinth is a reminder that the path matters as much as the destination.",
    "Music is the architecture of emotions, constructing bridges between hearts.",
    "The universe unfolds its stories in the constellations of the night sky.",
    "A candle's warmth reminds us that illumination can be a tender embrace.",
    "Perception is a kaleidoscope, where reality transforms with each turn of perspective."
]
